src/courses/urls.py
from django.urls import path

from .views import CourseListView, CourseDetailView, LessonDetailView

app_name = 'courses'
urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('<slug>/', CourseDetailView.as_view(), name='detail'),
    path('<course_slug>/<lesson_slug>/', LessonDetailView.as_view(), name='lesson-detail'),
]

src/memberships/urls.py
from django.urls import path

from .views import MembershipSelectView

app_name = 'memberships'
urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
]

src/vidsub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('memberships/', include('memberships.urls', namespace='memberships')),
    path('courses/', include('courses.urls', namespace='courses')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/courses/models.py
from django.db import models
from django.urls import reverse

from memberships.models import Membership

class Course(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    description = models.TextField()
    allowed_memberships = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')

class Lesson(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    position = models.IntegerField()
    video_url = models.CharField(max_length=200)
    thumbnail = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:lesson-detail', kwargs={
            'course_slug': self.course.slug,
            'lesson_slug': self.slug
        })

src/memberships/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save

import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

MEMBERSHIP_CHOICES = (
    ('Enterprise', 'ent'),
    ('Professional', 'pro'),
    ('Free', 'free')
)

class Membership(models.Model):
    slug = models.SlugField()
    membership_type = models.CharField(choices=MEMBERSHIP_CHOICES, default='Free', max_length=30)
    price = models.IntegerField(default=15)
    stripe_plan_id = models.CharField(max_length=40)

    def __str__(self):
        return self.membership_type

class UserMembership(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=40)
    membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.user.username

def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
    if created:
        UserMembership.objects.get_or_create(user=instance)
    user_membership, created = UserMembership.objects.get_or_create(user=instance)
    if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
        new_customer_id = stripe.Customer.create(email=instance.email)
        user_membership.stripe_customer_id = new_customer_id['id']
        user_membership.save()

post_save.connect(post_save_usermembership_create, sender=settings.AUTH_USER_MODEL)

class Subscription(models.Model):
    user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=40)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.user_membership.user.username

src/courses/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, View

from memberships.models import UserMembership
from .models import Course


class CourseListView(ListView):
    model = Course


class CourseDetailView(DetailView):
    model = Course


class LessonDetailView(View):
    def get(self, request, course_slug, lesson_slug, *args, **kwargs):
        course_qs = Course.objects.filter(slug=course_slug)
        if course_qs.exists():
            course = course_qs.first()

        lesson_qs = course.lessons.filter(slug=lesson_slug)
        if lesson_qs.exists():
            lesson = lesson_qs.first()

        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type

        course_allowed_mem_types = course.allowed_memberships.all()
        context = {
            'object': None
        }
        if course_allowed_mem_types.filter(membership_type=user_membership_type).exists():
            context = {'object': lesson}
        return render(request, "courses/lesson_detail.html", context)

src/memberships/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView

import stripe

from .models import Membership, UserMembership, Subscription

def get_user_membership(request):
    try:
        user_membership_qs = UserMembership.objects.get(user=request.user)
        return user_membership_qs
    except ObjectDoesNotExist:
        return None

def get_user_subscription(request):
    try:
        user_subscription_qs = Subscription.objects.filter(user_membership=get_user_membership(request))
        return user_subscription_qs
    except ObjectDoesNotExist:
        return None

def get_selected_membership(request):
    membership_type = request.session['selected_membership_type']
    selected_membership_qs = Membership.objects.filter(membership_type=membership_type)
    if selected_membership_qs.exists():
        return selected_membership_qs[0]
    else:
        return None

class MembershipSelectView(ListView):
    model = Membership

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        current_membership = get_user_membership(self.request)
        context['current_membership'] = str(current_membership.membership)
        return context

    def post(self, request, **kwargs):
        selected_membership_type = request.POST.get('membership_type')
        user_membership = get_user_membership(request)
        user_subscription = get_user_subscription(request)
        selected_membership_qs = Membership.objects.filter(membership_type=selected_membership_type)
        if selected_membership_qs.exists():
            selected_membership = selected_membership_qs[0]


        if user_membership.membership == selected_membership:
            if user_subscription != None:
                messages.info(request, 'This is your membership')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        request.session['selected_membership_type'] = selected_membership.membership_type
        return HttpResponseRedirect(reverse('memberships:payment'))

def PaymentView(request):
    user_membership = get_user_membership(request)
    selected_membership = get_selected_membership(request)
    publishKey = settings.STRIPE_PUBLISHABLE_KEY

src/courses/templates/courses/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">

    <title></title>
  </head>
  <body>
  {% include 'courses/messages.html' %}
  <div class="container">
      <ol class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li><a href="/profile">Profile</a></li>
          {% block post_detail_link %}
          {% endblock %}
          {% if not request.user.is_authenticated %}
          <li class="pull-right"><a href="/register">Register</a></li>
          <li class="pull-right"><a href="/login">Login</a></li>
          {% else %}
          <li class="pull-right"><a href="/memberships">Memberships</a></li>
            {% endif %}
      </ol>
  </div>
    {% block content %}
    {% endblock content %}

<!-- Latest compiled and minified JavaScript -->
    <script
        src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
    </script>
  </body>
</html>

src/courses/templates/courses/course_detail.html
   {% extends 'courses/base.html' %}

   {% block content %}
    <h3>{{ object.title }}</h3>
    <p>{{ object.description }}</p>
    {% for lesson in object.lessons %}
    <a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}</a>
    {% endfor %}

   {% endblock content %}

src/courses/templates/courses/course_list.html
{% extends 'courses/base.html' %}

{% block content %}

    <h1>Course List View page</h1>
    {% for object in object_list %}
        <a href="{{ object.get_absolute_url }}">{{ object }}</a>
    {% endfor %}

{% endblock content %}

src/courses/templates/courses/lesson_detail.html
   {% extends 'courses/base.html' %}

    {% block content %}
    <h2>Lesson Detail View</h2>
    {% if object is not None %}
    <h4>{{ object.title }}</h4>
    <p>{{ object.description }}</p>
    {% else %}
    <h3>Upgrade membership</h3>
    {% endif %}


    {% endblock content %}

src/courses/templates/courses/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

src/memberships/templates/memberships/membership_list.html
{% extends 'courses/base.html' %}

{% block content %}

    <div class="container">
        <h1>Select a membership</h1>
        <div class="row">
            {% for object in object_list %}
            <div class="col-sm-4 col-md-4">
                <h2>{{ object.membership_type }}</h2>
                <p>Price ${{ object.price }} <small>/month</small></p>
                <h4>Included courses</h4>
                <ul>
                    {% for course in object.course_set.all  %}
                    <li>{{ course.title }}</li>
                    {% endfor %}
                </ul>
                {% if object.membership_type != 'Free' %}
                <form method="POST" action="{% url 'memberships:select' %}"> {% csrf_token %}
                    {% if object.membership_type != current_membership %}
                    <button class="btn btn-warning">Select</button>
                    {% else %}
                    <small>This is your current membership</small>
                    {% endif %}
                    <input type="hidden" name="membership_type" value="{{ object.membership_type }}">
                </form>
                {% endif %}

            </div>

            {% endfor %}
        </div>
    </div>

{% endblock content %}